<a href="https://colab.research.google.com/github/ElectricPicklePlayer/mathLabs/blob/main/eersteOefeningen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones(10).reshape(2,3)

ValueError: cannot reshape array of size 10 into shape (2,3)

In [ ]:
np.ones(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(10).reshape(2,-1)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
z = np.array([[1.0,3,9],[3,4,5]])

In [ ]:
z.dtype

dtype('float64')

In [ ]:
z = np.array([1,2,5])
b = np.array([6,7,8])

In [ ]:
z + b

array([ 7,  9, 13])

In [ ]:
print(z+b)

[ 7  9 13]


In [ ]:
3* z

array([ 3,  6, 15])

In [ ]:
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
b = np.array([-1,-2,-3,-4,-5,-6])
b

array([-1, -2, -3, -4, -5, -6])

In [ ]:
a + b


array([[-1, -1, -1, -1, -1, -1],
       [ 5,  5,  5,  5,  5,  5],
       [11, 11, 11, 11, 11, 11],
       [17, 17, 17, 17, 17, 17]])

In [ ]:
c = np.array([-1,-2,-3,-4])
c

array([-1, -2, -3, -4])

In [ ]:
a + c

ValueError: operands could not be broadcast together with shapes (4,6) (4,) 

In [3]:
## Floating point error

0.1 + 0.2 == 0.3

False

In [5]:
import math

math.isclose(0.1+0.2, 0.3)

True